### PR TITLE
Update boot.s

### PR DESCRIPTION
**Pull request by Creeplays**

### CODE REVIEW

**Comment by Creeplays** [comment]
@assusdan, write code for interrupt handling yourself

**Comment by assusdan** [comment]
@Creeplays pls help me bro

**Comment by Creeplays** [comment]
Pls do it yourself
05.11.2016 19:37 пользователь "Suslov Danila" <notifications@github.com>
написал:

**Comment by assusdan** [comment]
Oh sh*t I'll do it when I finish my recent work

**Pull request merged**
